const modules=[
{title:'Safety & PPE',desc:'Shock, arc-flash, fire, lockout/tagout, ladders, and hazard recognition.',tag:'OSHA foundation'},
{title:'Electrical Theory',desc:'Voltage, current, resistance, power, AC/DC, series and parallel circuits.',tag:'Core math'},
{title:'Tools & Meters',desc:'Hand tools, testers, multimeters, safe inspection, and tool care.',tag:'Shop skills'},
{title:'Conductors & Wiring',desc:'Wire types, insulation, cable assemblies, boxes, raceways, and terminations.',tag:'Installation'},
{title:'Residential Systems',desc:'Branch circuits, receptacles, lighting, GFCI/AFCI concepts, and panels.',tag:'Dwelling wiring'},
{title:'Commercial Systems',desc:'Three-phase basics, conduit, motors, transformers, and control concepts.',tag:'Commercial'},
{title:'Code & Blueprints',desc:'NEC organization, plan symbols, load calculations, and local amendments.',tag:'Exam prep'},
{title:'Troubleshooting',desc:'A repeatable method for finding faults without guessing or bypassing safety.',tag:'Diagnostics'}
];
const lessons=[
{title:'Safety: Establish an Electrically Safe Work Condition',intro:'The safest circuit is one that has been properly de-energized, isolated, locked out, and verified before work begins.',diagram:`<svg viewBox="0 0 760 230" width="100%" role="img" aria-label="Lockout tagout verification flow"><defs><marker id="a" markerWidth="10" markerHeight="10" refX="6" refY="3" orient="auto"><path d="M0,0 L0,6 L7,3 z" fill="#142633"/></marker></defs><g font-family="Inter" text-anchor="middle"><rect x="20" y="75" width="120" height="70" rx="12" fill="#ffd54a"/><text x="80" y="104" font-weight="700">Identify</text><text x="80" y="126" font-size="13">all energy sources</text><path d="M145 110H205" stroke="#142633" stroke-width="4" marker-end="url(#a)"/><rect x="215" y="75" width="120" height="70" rx="12" fill="#dfe8ec"/><text x="275" y="104" font-weight="700">Disconnect</text><text x="275" y="126" font-size="13">and isolate</text><path d="M340 110H400" stroke="#142633" stroke-width="4" marker-end="url(#a)"/><rect x="410" y="75" width="120" height="70" rx="12" fill="#dfe8ec"/><text x="470" y="104" font-weight="700">Lock & tag</text><text x="470" y="126" font-size="13">prevent restart</text><path d="M535 110H595" stroke="#142633" stroke-width="4" marker-end="url(#a)"/><rect x="605" y="75" width="135" height="70" rx="12" fill="#cdebdc"/><text x="672" y="104" font-weight="700">Verify absence</text><text x="672" y="126" font-size="13">with rated tester</text></g></svg>`,steps:['Identify every possible source of electrical energy and all affected equipment.','Notify affected people and shut the equipment down normally.','Open the disconnecting means and apply personal locks and tags according to the employer procedure.','Release or restrain stored energy.','Use an adequately rated tester. Prove the tester on a known source, test the circuit, then prove the tester again.','Only a qualified person following the applicable procedure should begin work.'],tip:'“Breaker off” is not the same as verified de-energized. Mislabeling, backfeed, and failed devices are real hazards.'},
{title:'Ohm’s Law and Electrical Power',intro:'Four relationships solve many entry-level exam questions: V = I × R, I = V ÷ R, R = V ÷ I, and P = V × I.',diagram:`<svg viewBox="0 0 760 260" width="100%" role="img" aria-label="Simple DC circuit"><g font-family="Inter"><line x1="150" y1="55" x2="550" y2="55" stroke="#142633" stroke-width="6"/><line x1="550" y1="55" x2="550" y2="205" stroke="#142633" stroke-width="6"/><line x1="550" y1="205" x2="150" y2="205" stroke="#142633" stroke-width="6"/><line x1="150" y1="205" x2="150" y2="55" stroke="#142633" stroke-width="6"/><line x1="135" y1="105" x2="165" y2="105" stroke="#142633" stroke-width="5"/><line x1="125" y1="145" x2="175" y2="145" stroke="#142633" stroke-width="9"/><text x="85" y="130" font-weight="700">12 V</text><polyline points="300,55 320,35 340,75 360,35 380,75 400,35 420,55" fill="none" stroke="#c7473b" stroke-width="5"/><text x="360" y="105" text-anchor="middle" font-weight="700">6 Ω load</text><path d="M450 180 C395 220,310 220,255 180" fill="none" stroke="#2f8f61" stroke-width="4"/><text x="350" y="245" text-anchor="middle" font-weight="700">Current = 12 ÷ 6 = 2 A</text></g></svg>`,steps:['Write down the known quantities and their units.','Select the formula containing the unknown value.','Substitute numbers before doing arithmetic.','Calculate and attach the correct unit.','Check whether the answer is physically reasonable.'],tip:'Example: a 1,440-watt load at 120 volts draws 12 amperes because I = P ÷ V.'},
{title:'Series and Parallel Circuits',intro:'Series components share current. Parallel branches share voltage. Building wiring loads are generally connected in parallel so each load receives rated voltage.',diagram:`<svg viewBox="0 0 760 320" width="100%" role="img" aria-label="Series and parallel circuit comparison"><g font-family="Inter"><text x="190" y="32" font-size="20" font-weight="800" text-anchor="middle">SERIES</text><path d="M55 100H135 M245 100H325V245H55V100" fill="none" stroke="#142633" stroke-width="5"/><rect x="135" y="75" width="110" height="50" rx="8" fill="#ffd54a"/><text x="190" y="106" text-anchor="middle">R1</text><rect x="135" y="220" width="110" height="50" rx="8" fill="#ffd54a"/><text x="190" y="251" text-anchor="middle">R2</text><text x="190" y="300" text-anchor="middle">Same current</text><text x="565" y="32" font-size="20" font-weight="800" text-anchor="middle">PARALLEL</text><path d="M430 100H700 M430 245H700 M460 100V245 M670 100V245" fill="none" stroke="#142633" stroke-width="5"/><rect x="505" y="75" width="110" height="50" rx="8" fill="#cdebdc"/><text x="560" y="106" text-anchor="middle">R1</text><rect x="505" y="220" width="110" height="50" rx="8" fill="#cdebdc"/><text x="560" y="251" text-anchor="middle">R2</text><text x="565" y="300" text-anchor="middle">Same voltage</text></g></svg>`,steps:['Sketch the source and every load.','Mark junctions where current can split.','For series resistance, add resistances directly.','For parallel branches, calculate branch current separately or use the reciprocal resistance formula.','Confirm total current equals the sum of branch currents.'],tip:'Opening one parallel branch normally leaves the other branches operating; opening a series path stops current everywhere.'},
{title:'Receptacle Anatomy and Grounding',intro:'A standard receptacle has an ungrounded (hot) side, a grounded conductor (neutral) side, and an equipment grounding connection. Color and terminal conventions aid identification but must never replace testing.',diagram:`<svg viewBox="0 0 760 320" width="100%" role="img" aria-label="Receptacle terminal diagram"><g font-family="Inter"><rect x="280" y="25" width="200" height="270" rx="35" fill="#fff" stroke="#142633" stroke-width="6"/><rect x="325" y="75" width="25" height="70" rx="10" fill="#142633"/><rect x="410" y="75" width="25" height="70" rx="10" fill="#142633"/><circle cx="380" cy="190" r="21" fill="none" stroke="#142633" stroke-width="8"/><line x1="250" y1="95" x2="280" y2="95" stroke="#c2a33d" stroke-width="12"/><text x="195" y="100" text-anchor="end" font-weight="700">Brass: ungrounded</text><line x1="480" y1="95" x2="510" y2="95" stroke="#b9c3c8" stroke-width="12"/><text x="530" y="100" font-weight="700">Silver: grounded</text><line x1="380" y1="295" x2="380" y2="315" stroke="#2f8f61" stroke-width="12"/><text x="380" y="315" text-anchor="middle" dy="18" font-weight="700">Green: equipment ground</text></g></svg>`,steps:['Use only a purpose-built, unplugged training board or low-voltage simulator.','Identify the brass, silver, and green terminal locations.','Practice making a clockwise conductor hook on scrap wire with the correct tool.','Inspect for damaged insulation, excessive exposed copper, loose strands, and poor mechanical connection.','Have a qualified instructor inspect the work before any training board is energized.'],tip:'The grounded conductor is normally white or gray; the equipment grounding conductor is green, green/yellow, or bare. Local rules and special cases still apply.'},
{title:'Reading a One-Line Diagram',intro:'A one-line diagram reduces a power-distribution system to its essential path: source, disconnect, protection, conductors, distribution equipment, and loads.',diagram:`<svg viewBox="0 0 760 230" width="100%" role="img" aria-label="Electrical one-line diagram"><g font-family="Inter" text-anchor="middle"><circle cx="80" cy="110" r="42" fill="#ffd54a" stroke="#142633" stroke-width="4"/><text x="80" y="106" font-weight="800">UTILITY</text><text x="80" y="126" font-size="12">SOURCE</text><line x1="122" y1="110" x2="205" y2="110" stroke="#142633" stroke-width="5"/><rect x="205" y="68" width="105" height="84" rx="10" fill="#fff" stroke="#142633" stroke-width="4"/><text x="257" y="106" font-weight="800">MAIN</text><text x="257" y="127" font-size="12">DISCONNECT</text><line x1="310" y1="110" x2="390" y2="110" stroke="#142633" stroke-width="5"/><rect x="390" y="55" width="115" height="110" rx="10" fill="#dfe8ec" stroke="#142633" stroke-width="4"/><text x="448" y="106" font-weight="800">PANEL</text><text x="448" y="127" font-size="12">BOARD</text><line x1="505" y1="110" x2="575" y2="110" stroke="#142633" stroke-width="5"/><line x1="575" y1="50" x2="575" y2="175" stroke="#142633" stroke-width="5"/><line x1="575" y1="50" x2="670" y2="50" stroke="#142633" stroke-width="4"/><line x1="575" y1="110" x2="670" y2="110" stroke="#142633" stroke-width="4"/><line x1="575" y1="175" x2="670" y2="175" stroke="#142633" stroke-width="4"/><text x="705" y="55">LIGHTS</text><text x="705" y="115">RECEPT.</text><text x="705" y="180">EQUIP.</text></g></svg>`,steps:['Begin at the source and trace downstream.','Identify every disconnecting means and protective device.','Note voltage, phase, conductor count, and equipment ratings.','Trace each feeder and branch circuit to its load.','Compare the diagram with schedules, floor plans, and specifications.'],tip:'A one-line diagram shows relationships, not physical routing or exact conductor placement.'}
];
const quiz=[
{q:'What is the safest first assumption about an electrical conductor?',a:['It is energized until proven otherwise','It is safe if the switch is off','It is safe if insulation looks intact','It is safe below 240 volts'],c:0,e:'Treat conductors as energized until an electrically safe work condition has been established and absence of voltage is verified.'},
{q:'A 1,200-watt load operates at 120 volts. Approximately how much current does it draw?',a:['5 A','10 A','12 A','100 A'],c:1,e:'I = P ÷ V = 1,200 ÷ 120 = 10 amperes.'},
{q:'In a parallel circuit, what quantity is the same across each branch?',a:['Resistance','Current','Voltage','Power'],c:2,e:'Each parallel branch is connected across the same two nodes, so branch voltage is the same.'},
{q:'Which device is primarily intended to protect people from ground-fault shock?',a:['GFCI','Standard toggle switch','Junction box','Wire nut'],c:0,e:'A GFCI detects an imbalance between outgoing and returning current and opens the circuit rapidly.'},
{q:'What should you do before and after testing a circuit for absence of voltage?',a:['Shake the meter','Prove the tester on a known source','Replace the breaker','Touch conductors together'],c:1,e:'The live-dead-live method verifies the tester function before and after the circuit test.'},
{q:'Most state electrician licensing exams draw heavily from which publication?',a:['International Plumbing Code','National Electrical Code','Vehicle Code','OSHA injury log'],c:1,e:'Licensing exams typically cover the adopted NEC edition plus state and local rules.'},
{q:'What does an overcurrent protective device primarily protect?',a:['The conductor and equipment from excessive current','A person from every possible shock','Only the receptacle face','The utility transformer only'],c:0,e:'Fuses and circuit breakers are selected to protect conductors and equipment from overcurrent conditions.'},
{q:'Why are household loads connected in parallel?',a:['To divide voltage among all appliances','So each load receives the supply voltage and operates independently','To increase total resistance without limit','To eliminate overcurrent protection'],c:1,e:'Parallel connection provides rated voltage to each load and allows independent operation.'},
{q:'Which pathway is most typical for becoming a journey-level electrician?',a:['Online videos only','A supervised apprenticeship with classroom instruction','One weekend seminar','Buying tools and starting immediately'],c:1,e:'Most electricians learn through multi-year apprenticeships combining paid work and technical instruction.'},
{q:'Who determines the enforceable electrical rules for a project?',a:['Any online course','The authority having jurisdiction and adopted codes','The equipment owner alone','The wire manufacturer alone'],c:1,e:'The AHJ enforces the adopted code and local amendments; product instructions and other regulations also apply.'}
];
let completed=JSON.parse(localStorage.getItem('cpCompleted')||'[]');let activeLesson=0;let qIndex=0;let answers=JSON.parse(localStorage.getItem('cpAnswers')||'{}');
function renderModules(){const grid=document.getElementById('moduleGrid');grid.innerHTML=modules.map((m,i)=>`<article class="module"><span class="done">${completed.includes(i)?'✓':''}</span><div class="num">0${i+1}</div><h3>${m.title}</h3><p>${m.desc}</p><span class="tag">${m.tag}</span><button onclick="openModule(${i})">${completed.includes(i)?'Review module':'Open module'}</button></article>`).join('');updateProgress()}
function openModule(i){activeLesson=Math.min(i,lessons.length-1);document.querySelector('#lesson').scrollIntoView();renderLessons();if(!completed.includes(i)){completed.push(i);localStorage.setItem('cpCompleted',JSON.stringify(completed));renderModules()}}
function renderLessons(){document.getElementById('lessonMenu').innerHTML=lessons.map((l,i)=>`<button class="${i===activeLesson?'active':''}" onclick="activeLesson=${i};renderLessons()">${i+1}. ${l.title.split(':')[0]}</button>`).join('');const l=lessons[activeLesson];document.getElementById('lessonContent').innerHTML=`<div class="eyebrow" style="color:#806200">Lesson ${activeLesson+1}</div><h2>${l.title}</h2><p>${l.intro}</p><div class="diagram">${l.diagram}</div><h3>Safe step-by-step practice</h3><div class="steps">${l.steps.map(s=>`<div class="step"><div>${s}</div></div>`).join('')}</div><div class="callout" style="margin-top:20px"><b>Exam and field note:</b> ${l.tip}</div>`}
function updateProgress(){const pct=Math.round(completed.length/modules.length*100);document.getElementById('headerProgress').textContent=pct+'%';document.getElementById('heroMeter').style.width=pct+'%';document.getElementById('moduleCount').textContent=`${completed.length} of ${modules.length}`}
function renderQuiz(){const item=quiz[qIndex];document.getElementById('quizStatus').innerHTML=`<div style="display:flex;justify-content:space-between;margin-bottom:18px;color:#66737d"><b>Question ${qIndex+1} of ${quiz.length}</b><span>${Object.keys(answers).length} answered</span></div>`;document.getElementById('question').textContent=item.q;document.getElementById('answers').innerHTML=item.a.map((x,i)=>`<button class="answer ${answers[qIndex]!==undefined?(i===item.c?'correct':(i===answers[qIndex]?'wrong':'')):''}" onclick="chooseAnswer(${i})">${String.fromCharCode(65+i)}. ${x}</button>`).join('');document.getElementById('feedback').textContent=answers[qIndex]!==undefined?item.e:'';document.getElementById('prevBtn').disabled=qIndex===0;document.getElementById('nextBtn').textContent=qIndex===quiz.length-1?'Show score':'Next'}
function chooseAnswer(i){answers[qIndex]=i;localStorage.setItem('cpAnswers',JSON.stringify(answers));renderQuiz()}
document.getElementById('prevBtn').onclick=()=>{if(qIndex>0){qIndex--;renderQuiz()}};document.getElementById('nextBtn').onclick=()=>{if(qIndex<quiz.length-1){qIndex++;renderQuiz()}else{const score=quiz.reduce((n,x,i)=>n+(answers[i]===x.c),0);const pct=Math.round(score/quiz.length*100);document.getElementById('question').innerHTML=`Your score: ${score}/${quiz.length} (${pct}%)`;document.getElementById('answers').innerHTML=pct>=80?'<div class="callout"><b>Completion badge unlocked.</b><br>You have passed this foundation practice test. Continue with supervised hands-on training and your jurisdiction’s official exam materials.</div>':'<div class="warning"><b>Keep studying.</b><br>Review the explanations, complete the lessons, and retake the test. Licensing exams often require codebook navigation as well as calculations.</div>';document.getElementById('feedback').textContent='';document.querySelector('.quiz-nav').classList.add('hide')}};
document.getElementById('stateSelect').onchange=e=>{const s=e.target.value;const map={California:'California has separate pathways for electrician certification and electrical contractor licensing. Verify trainee registration, required experience, exam classifications, and current rules with the California Department of Industrial Relations and Contractors State License Board.', 'North Carolina':'North Carolina regulates electrical contracting through the State Board of Examiners of Electrical Contractors. Employee and contractor requirements differ, so verify classification, experience, and examination rules directly with the board.',Texas:'Texas electrician licensing is administered by the Texas Department of Licensing and Regulation. Verify apprentice, residential wireman, journeyman, master, and contractor requirements.',Florida:'Florida licensing may be state-certified or locally registered depending on the work and jurisdiction. Confirm requirements with the Florida Department of Business and Professional Regulation and the local authority.', 'New York':'New York does not use one statewide electrician license for all work; many cities and local jurisdictions license electricians. Check the municipality where you intend to work.','Other / local jurisdiction':'Search your state licensing agency, city or county building department, and apprenticeship office. Confirm the adopted NEC edition, experience hours, exam provider, and renewal rules.'};document.getElementById('stateInfo').textContent=map[s]||'Select a state to see the correct licensing approach.'}
renderModules();renderLessons();renderQuiz();
